USE chat_app;

SELECT 
    F.ID AS FRIENDSHIP_ID, 
    M.NAME AS FRIEND_NAME, 
    M.PROFILE AS FRIEND_PROFILE
FROM FRIENDS F
JOIN MEMBER M ON F.FRIEND_ID = M.ID
WHERE F.USER_ID = 'user1' AND F.STATUS = 'accepted';

