USE chat_app;

SELECT * FROM MEMBER;

SELECT * FROM FRIENDS;

SELECT * FROM ROOM;

SELECT * FROM ROOM_MEMBER;

SELECT * FROM MESSAGE;

SELECT * FROM EMOJI;

SELECT * FROM EMOJI_LOG;

INSERT INTO MESSAG (ROOM_ID, SEND, CONTENT, TIME) VALUES ("1", user1, "다음에 뵈요", NOW)
